#!/bin/bash

BASE_PATH="$(git rev-parse --show-toplevel)"
STAGED_CONFIG_FILES="$(git diff --cached --diff-filter=ACMR --oneline --name-only --relative -- 'setup.*')"
if [ -n "$STAGED_CONFIG_FILES" ]; then
    echo "Changed config files, run tests/lint on all files"
    STAGED_PY_FILES="$BASE_PATH"
else
    STAGED_PY_FILES="$(git diff --cached --diff-filter=ACMR --oneline --name-only --relative -- '*.py')"
fi

FLAKE8=`which flake8`

function test_dependencies {
    if ! type $FLAKE8 &> /dev/null; then
      printf "\033[41mPlease install Flake8\033[0m\n"
      return 1
    fi

    return 0
}

function call_flake8 {
    if [ -z "$STAGED_PY_FILES" ]; then
        echo "No python files changed, nothing to lint with flake8"
        return 0
    fi

    echo "Linting Python files with Flake8 ($FLAKE8)"

    $FLAKE8 --config $BASE_PATH/setup.cfg $STAGED_PY_FILES
    FLAKE8_EXIT=$?

    if [[ "${FLAKE8_EXIT}" == 0 ]]; then
      printf "\033[42mFLAKE8 SUCCEEDED\033[0m\n"
    else
      printf "\033[41mFLAKE8 FAILED:\033[0m Fix flake8 errors and try again\n"
      return 1
    fi

    return 0
}

function test_coverage {
    if [ -z "$STAGED_PY_FILES" ]; then
        echo "No python files changed, nothing to nosetests"
        return 0
    fi

    rm -fr .coverage cover
    ./setup.py nosetests
    COVERAGE_EXIT=$?

    if [[ "${COVERAGE_EXIT}" == 0 ]]; then
      printf "\033[42mCOVERAGE SUCCEEDED\033[0m\n"
    else
      printf "\033[41mCOVERAGE FAILED:\033[0m Fix coverage errors and try again\n"
      return 1
    fi

    return 0
}

function check_examples {
    if [ -z "$STAGED_PY_FILES" ]; then
        echo "No python files changed, nothing to check in examples"
        return 0
    fi

    (cd $BASE_PATH/examples/github &&
        NO_DOWNLOAD=1 ./update-schema.sh &&
        ./update-operations.sh &&
        echo 'GitHub example Ok')
    (cd $BASE_PATH/examples/shopify &&
        NO_DOWNLOAD=1 ./update-schema.sh &&
        ./update-operations.sh &&
        echo 'Shopify example Ok')
}

cd $BASE_PATH
test_dependencies &&
call_flake8 &&
check_examples &&
test_coverage
