version: 2
formats: all

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs

sphinx:
   configuration: doc/source/conf.py
