query ListIssues($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
        issues(first: 100) {
            nodes {
                n: number
                title
            }
            pageInfo {
                hasNextPage
                endCursor
            }
        }
    }
}
